
CC = {
["Aatrox"] 			= 	{ {["slot"] = _Q , ["spellName"] = "AatroxQ"			, ["spellType"] = "circular" 	, ["projectileSpeed"] = 450	, ["spellDelay"] = 250	, ["spellRange"] = 650	, ["spellRadius"] = 285	, ["collision"] = false	}, 
					{  ["slot"] = _E , ["spellName"] = "AatroxE"			, ["spellType"] = "line" 	, ["projectileSpeed"] = 1200	, ["spellDelay"] = 250	, ["spellRange"] = 1075	, ["spellRadius"] = 100	, ["collision"] = false	} },
["Ahri"] 			= 	{ {["slot"] = _E , ["spellName"] = "AhriSeduce"			, ["spellType"] = "line" 	, ["projectileSpeed"] = 1550	, ["spellDelay"] = 250	, ["spellRange"] = 1000	, ["spellRadius"] = 60	, ["collision"] = true	} }, 

}


CC = {
-- ["Aatrox"] 				= {_Q,_E},
-- ["Ahri"] 				= {_E},
["Alistar"]				= {_Q,_W},
["Amumu"] 				= {_Q,_R},
["Anivia"] 				= {_Q},
["Ashe"] 				= {_R},
["Bard"] 				= {_Q},
["Blitzcrank"] 			= {_Q,_E},
["Braum"] 				= {_Q,_R},
["Cassiopeia"] 			= {_R},
["ChoGath"]				= {_Q},
["Darius"] 				= {_W,_E},
["Diana"]				= {_E},
["DrMundo"] 			= {_Q},
["Draven"] 				= {_E},
["Elise"] 				= {_E},
["Evelynn"] 			= {_R},
["Fiddlesticks"] 		= {_Q},
["Fizz"] 				= {_R},
["Galio"] 				= {_Q,_R},
["Gnar"] 				= {_Q,_W,_R},
["Gragas"] 				= {_E,_R},
["Hecarim"] 			= {_R},
["Heimerdinger"] 		= {_E},
["Irelia"] 				= {_E},
["Janna"] 				= {_Q,_W},
["Karma"] 				= {_Q,_W},
["Kassadin"] 			= {_E},
["Kayle"] 				= {_Q},
["KhaZix"] 				= {_W},
["KogMaw"] 				= {_E},
["LeBlanc"] 			= {_E},
["LeeSin"] 				= {_R},
["Leona"] 				= {_Q,_R},
["Lissandra"] 			= {_Q,_R},
["Lulu"] 				= {_Q,_E},
["Lux"] 				= {_Q},
["Malphite"] 			= {_Q,_R},
["Malzahar"] 			= {_R},
["Maokai"] 				= {_Q,_W},
["Morgana"] 			= {_Q,_R},
["Nami"]				= {_Q,_R},
["Nasus"] 				= {_W},
["Nautilus"]			= {_Q,_R},
["Nocturne"] 			= {_E},
["Nunu"] 				= {_E},
["Olaf"] 				= {_Q},
["Orianna"]				= {_R},
["Pantheon"] 			= {_W},
["Poppy"] 				= {_E}, 
["Quinn"] 				= {_Q,_E},
["Rammus"] 				= {_E},
["Renekton"] 			= {_W},
["Rengar"] 				= {_E},
["Riven"] 				= {_W},
["Rumble"] 				= {_E},
["Ryze"] 				= {_W},
["Sejuani"] 			= {_Q,_E,_R},
["Shaco"] 				= {_E},
["Shen"] 				= {_E},
["Shyvana"] 			= {_R},
["Singed"] 				= {_E},
["Skarner"] 			= {_E,_R},
["Sona"] 				= {_R},
["Swain"] 				= {_Q,_W},
["Syndra"] 				= {_E,_W},
["TahmKench"] 			= {_Q,_E},
["Taric"] 				= {_E},
["Teemo"] 				= {_Q},
["Thresh"] 				= {_Q,_E},
["Tristana"] 			= {_R},
["Tryndamere"]			= {_W},
["Urgot"] 				= {_R},
["Varus"] 				= {_R},
["Vayne"] 				= {_E},
["Veigar"] 				= {_E},
["VelKoz"] 				= {_Q,_E},
["Vi"] 					= {_Q,_R},
["Viktor"] 				= {_W},
["Volibear"]	 		= {_Q},
["Warwick"]	 			= {_R},
["Xerath"] 				= {_E},
["Yasou"] 				= {_R},
["Zac"] 				= {_Q,_E},
["Ziggs"] 				= {_W},
["Zilean"] 				= {_Q,_W},
["Zyra"] 				= {_E,_R}
}



